void port_init (unsigned char port);
void DIO_vport_dir (unsigned char port, unsigned char pin, unsigned char dir);
void DIO_vwrite_PIN(unsigned char port_name, unsigned char DATA ,unsigned char pin_number);
void DIO_vtoggle_PIN(unsigned char port_name ,unsigned char pin_number);
unsigned char DIO_u8READ_PIN(unsigned char port_name ,unsigned char pin_number);
void DIO_setPortDir( unsigned char portName, unsigned char direction );
void DIO_writePort( unsigned char portName, unsigned char data);
unsigned char DIO_u8ReadPort( unsigned char portName);
void DIO_enablePullUp( unsigned char portName, unsigned char pinNo );
void DIO_u8WriteHighNibble ( unsigned char portName, unsigned char data);
void DIO_u8WriteLowNibble ( unsigned char portName, unsigned char data);
